### ISSUE TITLE
Random Crash Exiting the Inn in Winterhold.

### ISSUE THREAD

**Issue by jwzd96** [ixanza/Equanimity#1]
**Describe the bug**
Game CTD after exiting the Inn in Winterhold

[Crash_2020_7_27_18-56-36.txt](https://github.com/ixanza/Equanimity/files/4983314/Crash_2020_7_27_18-56-36.txt)

**To Reproduce**

1. Go to Winterhold Inn.
2. Talk to some people and leave.

**Expected behavior**
Normal Loading screen. 

**Modlist version**
Newest

**Did you add any additional mods?**

No.

**Comment by ixanza** [comment]
Can't replicate this. Seems to be a random crash. Please open a new issue if this is repeatable.

**Comment by Kaesoi** [comment]
Short version: Love Equanimity. Assume I'm a complete noob to modding. Got to around level 17. Did College of Winterhold questline. Crashes increased in frequency as I pursued questline. Game would crash every time I attacked/talked/interacted with the 2 enthralled wizards keeping Morokei contained (killed them with console to get around that). Game would easily crash when returning to Winterhold with Staff of Magnus (Crashes occured when I got closer to the college and the magic anomalies and college npcs battled, especially after closing Ancano's barrier with the Staff). I probably could've Fast traveled from COW Roof and waited for the cell(s) to reset. But I quit the play through cause I couldn't manage to exit the college and collect the loot without crashing.

(Long version I decided was too long)

Additional info: (Note: some of these details may be unimportant, but maybe they are, so I added them anyway.) No extra mods added. No mod configuration files were altered (As in like changing better vampires settings). GPU: Radeon 5700 XT (8 gb of VRAM). Processor: Ryzen 3800X. PSU: 1000W. RAM: 32gb. 

I'm going to give Equanimity another try, cause it brought back my interest in Skyrim for the glorious 17 levels. This seemed to be the most relevant place to put this comment. This comment exists to bring awareness that Winterhold's performance is sketchy in my experience, and apparently the person who started this posts's experience. My theory is that something altering the college and/or CoW questline could be causing these crashes.

**Comment by ixanza** [comment]
Grab me the crash logs that appear in the overwrite directory. That’ll help better

**Comment by Kaesoi** [comment]
> Grab me the crash logs that appear in the overwrite directory. That’ll help better

I deleted all those files when trying other modpacks. I'm gonna start another (equanimity) playthrough and if it happens again i'll send it. But where are the crash logs you would want? (for future reference). (My files are set up in the root like: C:\(equanimity files)\(lots of folders n stuff)\.
