### ISSUE TITLE
Blood texture doesn't match weapon texture of Dagger of Discipline

### ISSUE THREAD

**Issue by AronRyd** [ixanza/Equanimity#10]
**Describe the bug**
When attacking with the Dagger of Discipline found in the Dark Brotherhood hideout, the blood texture that appears doesn't align with the model of the weapon.

**To Reproduce**
Acquire the Dagger (4D004537) and hit something that bleeds repeatedly until sufficient blood splatter is applied to outline the mismatch

**Expected behavior**
See screenshot

**Screenshots**
https://i.imgur.com/KNGaDxX.png

**Modlist version**
2.1.0

**Did you add any additional mods?**
No. Only deviation from original install is an xEdit to Wintersun - Faiths of Skyrim.exp; 04437D22 WSN_Misc_Sithis_Boon1_Litem; LVLD - Chance None, from value 90 to value 60

**Comment by ixanza** [comment]
Known problem with the mesh of the weapon. Fixing it requires me to edit the mesh file itself which is out of my expertise
