### ISSUE TITLE
Skyrim_Particle_Patch_for_ENB-SSE download fail

### ISSUE THREAD

**Issue by IanHeinrich** [ixanza/Equanimity#11]
The above mod was updated, so the hash now fails during download.

version: 2.1.1

![image](https://user-images.githubusercontent.com/22004416/92591829-821a4f80-f296-11ea-81cb-7e4884ff499f.png)

**Comment by ArKanuK** [comment]
Same here -- tried downloading file manually -- hash is different -- found an old file of the same name and moved to Equanimity downloads folder but hash was different there too -- scoured Discord and Nexus Forums -- if only we could modify the hash for Wabbajack to read.

**Comment by ixanza** [comment]
Fixed

**Comment by Skorn1349** [comment]
i know this issue was recently closed but i have the same issue today

**Comment by ixanza** [comment]
> i know this issue was recently closed but i have the same issue today

It seems to have stealthily updated. If you’re on the discord grab it from the pinned message in serenity-support channel, if not let me know I’ll get you a mirror

**Comment by Skorn1349** [comment]
found it and seems to be working now thank you
