### ISSUE TITLE
Can I edit if I know what I'm doing

### ISSUE THREAD

**Issue by cheesemanhugs** [ixanza/Equanimity#15]
Sorry if this is the wrong place for this...

I know if I edit I'm void of support from you guys. I'm thinking about swapping out the perk mod if I don't like it. I'm confident that I'd have no problem removing adamant and replacing it plus whatever patches/ dependencies it might have and am fully willing to put in the time. That being said some modlist authors say NOT to edit there list BY ANY MEANS. Does the same apply here? I've been modding for 3 years and have made my share of stupid mistakes, that being said you can never be too cautious.

**Comment by ixanza** [comment]
Of course if you know what you're doing you can do whatever you want. I'm not going to stop you. We only frown upon editing when the user doesn't know what they're doing then install/remove 50 mods and complain about bugs. Feel free to do whatever you want to the list and I can even point you in the right direction if you need some guidance.
