### ISSUE TITLE
Unable to Download HG Hairdos SE

### ISSUE THREAD

**Issue by Kitrane** [ixanza/Equanimity#16]
As stated in the title, the HG Hairdos download doesn't work.

**Screenshots**
![image](https://user-images.githubusercontent.com/75707518/101561721-6e60b100-398b-11eb-9a2d-073855e86cdb.png)

I don't know if you have it download it from your own link or not but I tried the link on its own and it didn't work then either. Just in case it makes it easier here's the link for the SE version: https://mega.nz/folder/xwxwzaDI#J3oxuELfc50dftUKQiIcUg/file/csZHUKrY

**Comment by ixanza** [comment]
Thats a problem with the connection from WJ to MEGA, nothing I can do.
