### ISSUE TITLE
XPSME Animations bugged?

### ISSUE THREAD

**Issue by JonasTheNomad** [ixanza/Equanimity#18]
**Describe the bug**
Well, if you use some of the XPSME Styles like "Sword on back" and then draw your sword, it just teleports right into your hand.
If i remember correcty, this didnt happen in the older Version.
Might be a Mistake on my side, since im pretty new to modding but i followed the install guide and already tried to simply reinstall the List, sadly the Animation is still missing.
I checked the Discord and the Issues on Github and it seems like im the only one with that Problem? Feel free to delete my post if im just too dumb to install this correctly :")

(Excuse my English Skills, its not my native language, if i made any severe grammar mistakes let me know, i´ll try to fix that.)

**To Reproduce**
Select "Sword on back" in the XPSME MCM, equip a sword (Left Hand) and watch it teleport into your Hand

**Expected behavior**
It should display an Animation.

**Modlist version**
Update 3.6.0

**Did you add any additional mods?**
Nope

**Comment by ixanza** [comment]
Previously we used allgud for dual/left handed sheathes and while that worked better it was causing a lot of crashes for some people. Now we swapped to ecotone for dual sheath so that may be a limitation for it.

**Comment by JonasTheNomad** [comment]
Hmm, okay.
I really liked the Animations, too bad they caused crashes.
Thanks for your fast reply :)
