### ISSUE TITLE
Invisible Alchemy Lab in Saarthal

### ISSUE THREAD

**Issue by daffodilian** [ixanza/Equanimity#2]
**Describe the bug**
Invisible Alchemy lab.

**To Reproduce**

1. Go to The second cell of Saarthal, there's a little alcove when in the room before eye of magus boi
2. Do 'stub your toe on the alchemy lab because it's invisible'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.
![SkyrimSE 2020-08-01 22-10-31](https://user-images.githubusercontent.com/63564258/89113902-a9cefa00-d444-11ea-9cf6-df54470751ef.png)
![SkyrimSE 2020-08-01 22-10-21](https://user-images.githubusercontent.com/63564258/89113905-acc9ea80-d444-11ea-8e47-9c0248e21f17.png)
![SkyrimSE 2020-08-01 22-15-57](https://user-images.githubusercontent.com/63564258/89113906-adfb1780-d444-11ea-9924-d41552abed9d.png)
![SkyrimSE 2020-08-01 22-13-05](https://user-images.githubusercontent.com/63564258/89113907-b05d7180-d444-11ea-9dab-22f22076b0fe.png)

**Modlist version**
1.2.1

**Did you add any additional mods?**

**Comment by ixanza** [comment]
Fixed
