### ISSUE TITLE
Floaty mountain above bleakwind basin

### ISSUE THREAD

**Issue by daffodilian** [ixanza/Equanimity#6]
**Describe the bug**
a mountain that someone forgot to delete

**To Reproduce**

go to bleaking wind basin and look up

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.
![enb2020_8_22_23_03_18](https://user-images.githubusercontent.com/63564258/90980913-1c0a9a00-e52c-11ea-8933-ee7701820429.png)
![enb2020_8_22_23_02_51](https://user-images.githubusercontent.com/63564258/90980915-1dd45d80-e52c-11ea-9689-95d8d1f1c83f.png)
![enb2020_8_22_23_02_29](https://user-images.githubusercontent.com/63564258/90980917-2036b780-e52c-11ea-891b-69c68001d76a.png)-p

**Modlist version**
2.0.1

**Did you add any additional mods?**
nop.
have fun thx

**Comment by arielle-allice** [comment]
I have the same issue as well. Thought I'd help by adding the ref ID for you Xanza.
![bleakwind](https://user-images.githubusercontent.com/69109345/90984097-dc16d780-e56a-11ea-80f8-6b32b1914cfa.PNG)

**Comment by ixanza** [comment]
Yo thanks. and wtf .

**Comment by ixanza** [comment]
Deleted it from existence. will be removed in the next update thanks
