### ISSUE TITLE
Corpse preparation doesn't work

### ISSUE THREAD

**Issue by Epyrus1991** [ixanza/Equanimity#7]
**Description**
The perk Corpse preparation doesn't work, the reanimated undead still turn to an ash pile whenever they are killed or the time expire.

**To replicate it**
To replicate simply level up conjuration, take "Corpse preparation perk" and use it in a dead corpse and wait untill the effect wears off or the reanimated get killed. I have tested "Reanimate corpse" and "raise zombie" even on a new save.

**Expected behaviour**
The expected is that you can reanimate over and over the same corpse without it turning to ash when the effect expires or get killed.

**Modlist version**
2.0.1

**Did you add any additional mods?**
No, equanimity without anything else on top.

**Comment by ixanza** [comment]
Fixed in dev. Undeath was overwriting the secondary effects.
