### ISSUE TITLE
Made my own template because I'm helpful

### ISSUE THREAD

**Issue by Patchier** [ixanza/Equanimity#8]
**Mod(s) to add**
Reliquary of Myth and Unique Item Tweaks - Improved Miscellaneous Artifacts

**Mods to remove/replace**
Zim's Immersive Artifacts and associated patches

**Reason for request**
Even with the possible need for nerfing, I consider this combination superior to Zim's

**What does a liar do when they die?**
They lie still.

**Comment by PKYxReGiGiGaSx** [comment]
I agree with these assessments. I have been playing this mod combination for a while and suggested it for LS2, which is now using. I found only a few artifacts to be pretty overpowered like Auriel's Bow is really effective against dragons but only when outdoors during the day. However, indoors it worsts than most enchanted bows unless against the undead.

The author has nerfed quite a few items already, which were op in the past. My issue with Zim's is that it has too much feature creep and isn't that lore-friendly as it describes itself to be and doesn't overhaul nearly as many items as RoM does, which means only a quarter of unique items are even viable to use.

Also, the quality of the asset is much superior in Reliquary. Try comparing the one-handed Ebony Blade from both mods, and you'll see a huge quality difference between the two. RoM is undoubtedly much nicer looking.

**Comment by Binah1013** [comment]
I just downloaded and installed Equanimity. I can't sneak. When go into sneak mode, I can't move and apparently I'm floating a little bit.
