### ISSUE TITLE
Unable to Install current Modlist version. 

### ISSUE THREAD

**Issue by MisterB1969** [ixanza/Equanimity#9]
**Describe the bug**
Missing 1 Archive, There is no ENB Series 0.437 to download. Download Installation Fails. Cannot continue.

**To Reproduce**
1. Download Files. 

**Expected behavior**
To go to Installation after downloading. 

**Screenshots**
https://i.gyazo.com/2425cf3e8a5b1a717a16067d958b54fe.png

**Modlist version**
2.0.1

**Did you add any additional mods?**
No

**Comment by ixanza** [comment]
What version of wabbajack are you on?

**Comment by MisterB1969** [comment]
> What version of wabbajack are you on?

2.2.0.0

**Comment by ixanza** [comment]
Update. The latest version of wabbajack is 2.2.2.0 and this was fixed in 2.2.1.7
